### ISSUE TITLE
Wheels created on Windows contain useless files

### ISSUE THREAD

**Issue by kayhayen** [kayhayen/Nuitka#103]
Windows bdist_nuitka wheels contain a .lib and .exp file, both of which are useless and should not be included.

The files are small, but add only noise. Unsure if they are there for MSVC and/or MinGW64.

All it takes is to find the proper spot in ./nuitka/distutils/bdist_nuitka.py to delete them.

**Comment by kayhayen** [comment]
Instructing the MSVC to place the .exp and .lib into the ".build" folder will be the solution to this issue, just needs somebody to find out the options that will do it.

**Comment by brupelo** [comment]
@kayhayen : Please consider this little tweak:

    if msvc_mode:
        env.Append(CCFLAGS = ["/EHsc", "/J", "/Gd"])
        env.Append(LINKFLAGS = [
            "/INCREMENTAL:NO",
            "/IMPLIB:{}\\foo.lib".format(normalize_path(source_dir)),
            "/OUT:{}\\foo.dll".format(normalize_path(source_dir))
        ])

        print(env["LINKFLAGS"])
        # Stack size 4MB or 8MB, we need more than the default 1MB.
        if target_arch == "x86_64":
            env.Append(CCFLAGS = ["/F8388608"])
        else:
            env.Append(CCFLAGS = ["/F4194304"])

And now look at the generated link command from our SCons buddy:

    link /nologo /INCREMENTAL:NO /IMPLIB:D:\sources\personal\python\apps\console\pytools\pytools\build\packages\foox\webcolors.build\foo.lib /OUT:D:\sources\personal\python\apps\console\pytools\pytools\build\packages\foox\webcolors.build\foo.dll /dll /out:webcolors.pyd /implib:webcolors.lib /LIBPATH:D:\software\python364_32\libs Shlwapi.lib Shell32.lib python36.lib webcolors.build\module.webcolors.obj webcolors.build\__constants.obj webcolors.build\__constants_data.obj webcolors.build\__frozen.obj webcolors.build\__helpers.obj webcolors.build\__internal__.obj webcolors.build\CompiledCellType.obj webcolors.build\CompiledFunctionType.obj webcolors.build\CompiledMethodType.obj webcolors.build\CompiledGeneratorType.obj webcolors.build\CompiledCoroutineType.obj webcolors.build\CompiledAsyncgenType.obj webcolors.build\CompiledFrameType.obj webcolors.build\CompiledCodeHelpers.obj webcolors.build\InspectPatcher.obj webcolors.build\MetaPathBasedLoader.obj

Do you see that 2nd implib used? Well, it'll override the first one... so, do you know how to instruct SCons to not be that "smart" and let me use my own linker flags without overriding them :) ?

**Comment by kayhayen** [comment]
From a git grep "no_import_lib" I got the impression that env["no_import_lib"] = True might be workable, passing to "SharedLibrary" as that referenced commit does also might work. Kind of hard to find the code behind those things. It seems to affect things for all compilers (linkers), which would be very nice as its not just MSVC then.

**Comment by brupelo** [comment]
Haven't checked with other compilers but if you don't use `no_import_lib` the final link command generated by Scons for visual studio will contain an /IMPLIB. And that's unfortunate as that implib will override the one we want to use. 

For instance, imagine  `link /IMPLIB:good_path\fancy.lib  /IMPLIB:bad_path\fancy.lib`, in that example `bad_path\fancy.lib` would be used, that's why you need `no_import_lib`. Just a little clarification, both cl and link parse left to right and override the same parameters... which btw, makes sense.

**Comment by kayhayen** [comment]
But do we need it to create an implib ever, or will the compilation still succeed without it? If possible I would love to spare the linker from doing that IO in the first place if it's not needed. I don't know if they are required intermediate products though.

**Comment by brupelo** [comment]
@kayhayen End-user don't definitely need to these .lib nor .exp files at all. Unless they want to use directly the extension module (shared library) on their c/c++ projects, which of course, it's a really bad idea as these python extension modules are intended to use by python code. Anyway, let's see how the visual studio linker behaves so we can understand why this can't be avoided, consider this dummy example:

    #include <windows.h>

    #ifdef EXPORT
    #define API_FUNCTION __declspec(dllexport)
    #else
    #define API_FUNCTION
    #endif

    API_FUNCTION void foo() {
        MessageBox(NULL, "foo", "foo", MB_OK);
    }

    API_FUNCTION void bar() {
        MessageBox(NULL, "bar", "bar", MB_OK);
    }

    void baz() {
        MessageBox(NULL, "baz", "baz", MB_OK);
    }

Open a visual command prompt and try this:

    cl /c foo.cpp && link /dll foo.obj user32.lib

as you can see, in this particular case the linker hasn't created neither a .lib nor an .exp files because the dll in this case exporting anything (EXPORT macro is undefined).

Now, what happens if we do this instead?

    cl /c /DEXPORT foo.cpp && link /dll foo.obj user32.lib

In this case, foo.lib and foo.exp have been created because the dll is exporting symbols. These symbols are the ones that will be written in the PE header IMPORT sections of the executable trying to use them, not sure how familiar you're already are with windows portable executables but I strongly recommend you to take a look to this little [cheatsheet](http://web.cse.ohio-state.edu/~reeves.92/CSE2421/HelloWorldGoal.pdf), once you understand the PE file format making tools like debuggers, dependency analizers, linkers, ... All of that becomes second nature and there is no black magic involved anymore, everything makes sense ;)

Anyway, as far as I know the python extension modules will exporting symbols to be used by python import API so there is no way to prevent visual studio linker to avoid creating the .lib/.exp files (or at least there isn't any flag I know... unless i reverse the linker somehow and patch it, which it's totally out of scope). That's why using `IMPLIB:path_to_our_build_folder/resultpath.lib` is the best chance we got here, at least will give us a clean outcome with just the final python dll.

Hope this clarifies a little bit more about this subject. Another interesting thing is what these .lib and .exp files really are. Let me try to bring some light to it, consider this scenario, let's say you want to use a dll but you don't have any the .lib to instruct the linker which symbols to inject into your final exe but you still would like to use it on your project. Well, one possible way to overcome this is by using tools such as dumpbin (included with Visual studio).

For instance, build my previous example exporting the symbols and then just do `dumpbin /exports foo.dll`, you'll see exactly the exported symbols dumped. But... how do you usee this information to create a .lib? You just need to create a `foo.def` file like:

    EXPORTS
    ?bar@@YAXXZ
    ?foo@@YAXXZ

and then use another ms's tool called `lib`, so you just do `lib /def:foo.def /out:file_ready_to_be_included_on_my_project.lib`. And that's pretty much, you could use that dll that didn't include any .lib

I didn't talk about the exp file but this [answer](https://stackoverflow.com/a/2727056/3809375) is pretty good one, so take a look to it in case you want to know more about it.

Sorry I didn't answer with a yes or no but I felt it was necessary to bring a little bit of light about what these linker files are and why they're created by vs' linker. Haven't analized other linkers like the one shipped with gcc as basically I just use cl/link for almost all my c++ stuff but I'd expect it to have similar. In the past I recall I've used a really good linker with some asm/c stuff where you didn't need to use .lib files at all, it was called golink, that linker was great as you just need to specify the dll and already would know how to create the import table in the final executable examining the included dlls.

Anyway, at the end of the day is all about being a little bit familiar with file formats such as PE,COFF, once you know at least the basics all this stuff becomes crystal water.

If you've got any other question, please let me know.

Sorry about the long reply.... ;D

**Comment by brupelo** [comment]
Btw, do you know what happened with my PR, let me explain you what I did so maybe you see something wrong in my workflow:

 - I've created a new branch called `feature_implib` tracking upstream:develop (upstream would be this repository and origin would be my fork), I've modified the SConsSingleExe file, tested the thing making sure it worked as expected and then created a PR. Then I've realized my PR wasn't good enough as I was printing some useless stuff so I've pushed again to my fork and the PR updated itself, so far so good.
 - Once I've seen all tests had passed on the PR I've just cleaned my local repository and deleted this `feature_implib` branch...

So, is there anything wrong with this way to create PRs? Did I miss something? Weren't you be able to merge for some reason?

Thanks

**Comment by kayhayen** [comment]
@brupelo I was have to see your PR and I think you deleted it, when you deleted the branch, you seem to have pushed that deletion, so I found the commit still, but no PR anymore. I think you should have rebased the branch, or reset it, but not deleted.

Must also be your git config somehow, because branch deletions normally do not get pushed, definitely not the default.

anyway, if you create a new branch and PR, I will glady merge it!

**Comment by brupelo** [comment]
@kayhayen I see, mmm, ok. From now on then each time I want to include some stuff into nuitka I will create a new branch feature from `develop`, made my changes, test it, make PR, get your feedback, tweak it, push again, get your feedback, tweak it... And I'll wait till you merge the feature, just then I'll delete that feature  branch both locally and my fork. In this case, I assumed after the PR was ready to go it was ok to delete the stuff locally.

I will find some time to make a new PR today then, ty.
