### ISSUE TITLE
Specifying explicit modules/packages that aren't imported statically.

### ISSUE THREAD

**Issue by AnythingTechPro** [kayhayen/Nuitka#112]
I need to compile a few modules/packages that are not imported statically rather dynamically in the codebase, for example in module TestModule.py
```python
exec 'from testpackage import TestModule2'
```
however testpackage will be excluded from the final build since it is not statically imported and the compiler doesn't recognize that i want the package included... I tried using the option '--recurse-to=testpackage', however that did not seem to include the package either...

**Comment by kayhayen** [comment]
@AnythingTechPro I am shocked to see it not being listed in the help output, so this must be a optparse bug of some sorts or what. This is also an important addition to the user interface, and the default recommended way in the User Manual.

Very bad. I will look into this right now, and hopefully be able to find what is going on. I am not so sure, I want to switch to argparse just because of this, but I might, very annoying.

**Comment by kayhayen** [comment]
So the option group was created, got the options added, but wasn't added to the parser.

My expected result would be, option don't work, instead they only do not show up in the help output of the parser. Anyway, great find. I am tagging this with "question" still, as this is obviously a FAQ. But with it more prominently in --help output, and esp. before the --recurse options are encountered, it should be less needed.

Currently it's in the hotfix branch hotfix/0.5.32.8 along with other stuff. I am however going to make a git flow release later today, where it will then reach master/develop along with those fixes, that is overdue anyway.

**Comment by AnythingTechPro** [comment]
I also noticed by specifying packages and/or modules, this overrides all other recursion options.
