### ISSUE TITLE
How to I compile packages with nested extension modules

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#120]
Here's what I've tried:

    (py364_32) D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32>ptime nuitka --include-package=numpy --module d:\virtual_envs\py364_32\Lib\site-packages\numpy --verbose

    (py364_32) D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32>ls
    OpenGL.build  OpenGL.pyd  __version__.py  main.py  numpy.build  numpy.pyd

    (py364_32) D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32>python -c "import numpy"
    Traceback (most recent call last):
      File "D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32\numpy\core\__init__.py", line 16, in <module numpy.core>
    ImportError: cannot import name 'multiarray'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32\numpy\__init__.py", line 142, in <module numpy>
      File "D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32\numpy\add_newdocs.py", line 13, in <module numpy.add_newdocs>
      File "D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32\numpy\lib\__init__.py", line 8, in <module numpy.lib>
      File "D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32\numpy\lib\type_check.py", line 11, in <module numpy.lib.type_check>
      File "D:\sources\personal\python\apps\console\pytools\pytools\build\packages\364_32\numpy\core\__init__.py", line 26, in <module numpy.core>
    ImportError:
    Importing the multiarray numpy extension module failed.  Most
    likely you are trying to import a failed build of numpy.
    If you're working with a numpy git repo, try `git clean -xdf` (removes all
    files not under version control).  Otherwise reinstall numpy.

    Original error was: cannot import name 'multiarray'

Any idea about this error and how to fix it? Please let me know, here's the [log](https://www.dropbox.com/s/ten9lobh59lb0vb/out.txt?dl=1) btw. Used latest nuitka.

Can you reproduce it?

**Comment by brupelo** [comment]
Here's the [log](https://www.dropbox.com/s/ten9lobh59lb0vb/out.txt?dl=1)

**Comment by brupelo** [comment]
@kayhayen Sorry about this report, please don't take a look to it, this one is totally my fault, in one of my multiple experiments messing around with nuitka I'd forgotten I'd modified MainControl with some custom options, ie:

<details><summary>CustomMainControl.py</summary>
<p>

    def main():
        """ Main program flow of Nuitka

            At this point, options will be parsed already, Nuitka will be executing
            in the desired version of Python with desired flags, and we just get
            to execute the task assigned.

            We might be asked to only re-compile generated C, dump only an XML
            representation of the internal node tree after optimization, etc.
        """

        print("[Building]")

        main_module = createMainModule()

        if Options.shallDumpBuiltTreeXML():
            # XML only.
            for module in ModuleRegistry.getDoneModules():
                dumpTreeXML(module)
        elif Options.shallDisplayBuiltTree():
            # GUI only.
            displayTree(main_module)
        else:
            with Prof("compileTree: %.2fs"):
                # Make the actual compilation.
                result, options = compileTree(
                    main_module = main_module
                )
                dist_dir = getStandaloneDirectoryPath(main_module)
                source_dir = getSourceDirectoryPath(main_module)
                standalone_dir = getStandaloneDirectoryPath(main_module)

            # Exit if compilation failed.
            if not result:
                sys.exit(1)

            if Options.shallNotDoExecCCompilerCall():
                if Options.isShowMemory():
                    MemoryUsage.showMemoryTrace()

                sys.exit(0)

            if not Options.options.exec_freezer:
                return

            if Options.isStandaloneMode():
                print("[Freezing]")

                with Prof("freezeProject: %.2fs"):
                    freezeProject(options, source_dir, dist_dir, standalone_dir)

            # Remove the source directory (now build directory too) if asked to.
            if Options.isRemoveBuildDir():
                removeDirectory(
                    path          = getSourceDirectoryPath(main_module),
                    ignore_errors = False
                )

            # Modules should not be executable, but Scons creates them like it, fix
            # it up here.
            if Utils.getOS() != "Windows" and Options.shallMakeModule():
                subprocess.call(
                    (
                        "chmod",
                        "-x",
                        getResultFullpath(main_module)
                    )
                )

            if Options.shallMakeModule() and Options.shallCreatePyiFile():
                pyi_filename = getResultBasepath(main_module) + ".pyi"

                with open(pyi_filename, 'w') as pyi_file:
                    pyi_file.write(
                        """\
    # This file was generated by Nuitka and describes the types of the
    # created shared library.

    # At this time it lists only the imports made and can be used by the
    # tools that bundle libraries, including Nuitka itself. For instance
    # standalone mode usage of the created library will need it.

    # In the future, this will also contain type information for values
    # in the module, so IDEs will use this. Therfore please include it
    # when you make software releases of the extension module that it
    # describes.

    %(imports)s

    # This is not Python source even if it looks so. Make it clear for
    # now. This was decided by PEP 484 designers.
    __name__ = ...

    """ % {
                            "imports" : '\n'.join(
                                "import %s" % module_name
                                for module_name in
                                getImportedNames()
                            )

                        }
                    )


            # Execute the module immediately if option was given.
            if Options.shallExecuteImmediately():
                if Options.shallMakeModule():
                    executeModule(
                        tree       = main_module,
                        clean_path = Options.shallClearPythonPathEnvironment()
                    )
                else:
                    executeMain(
                        binary_filename = getResultFullpath(main_module),
                        clean_path      = Options.shallClearPythonPathEnvironment()
                    )

</p>
</details>
<p></p>

I was defaulting `Options.options.exec_freezer` to false as I wasn't interested on the below code when creating standalone exe but didn't realize there was necessary code to create the extension modules.

Totally my bad, sorry... haven't tried yet with the original nuitka but I assume it'll be able to ship the numpy extension modules correctly, forget about this one. Closing

**Comment by kayhayen** [comment]
The numpy is known to work in standalone mode. I doubt it has been compiled that way yet.

The resulting package mostly likely will not integrate well with an existing "numpy" package, that would have to provide the "multiarray" module, which is an extension module and not included in the "numpy.pyd" you create.

For the package "numpy", the code is run in "createPathAssignment", where there is two options, one is original "__path__" which will make your numpy.pyd look up stuff to import in the original location. I think it should still prefer embedded modules though, but I am not 100% certain right now.

And then there is the other mode, which will put the ".pyd" file system location in its "__path__" as well as something found in environment variable "NUITKA_PACKAGE_numpy". That is actually how "pytest" is supposed to extend package name spaces with test code. It's not documented yet, but works.

So if you were to manually copy the .pyd file for multprocesing it ought to work:

Your filesystem will look like this:

numpy.pyd
numpy/core/multiarray.pyd

Ok, not sure now if the "numpy" folder is to be used or not, would have to be tested.

That is also how datafiles are working, I think "pgk_resources" goes via __file__ or __path__ too.

Maybe for "package mode", which there currently not really is one, the gathering of extension modules, and more generally consideration for copying non sources as data files could be added. I am not there yet.

My thinking however was that these things are something the "setup.py" of existing numpy code for distutils will already do. And that I mean to focus on getting that to work. So using "bdist_nuitka" target on the original source distribution should be what is used, instead of trying to re-package the packaged result. I am thinking that nested ".pyd" thing is kind of crap nobody does who isn't doing distutils already anyway.

Yours,
Kay

**Comment by kayhayen** [comment]
@brupelo you are getting there.

First of all, the win32 package is a mean thing that does some weird thing, that even caused me to hard code in the importing mechanic:

```
        def getPackageDirCandidates(element):
            yield os.path.join(element, package_name), False

            # Hack for PyWin32. TODO: Move this "__path__" extensions to be
            # plug-in decisions.
            if package_name == "win32com":
                yield os.path.join(element, "win32comext"), True

```

That kind of code aims at producing a workable "__path__" and the win32 package is polluting name space, that is why you found --recurse-all necessary. That is of course bad stuff. Just avoid it if you can.

As for numpy working on second import. There is no cleanup for a failed import in Python for extension modules, unless they follow complicated stuff. But the usual extension module normally rather crashes your process anyway, error checking is at least partially invented for numpy, so it is relatively good.

That actually has nothing to do with Nuitka, happens with normal Python too.

Like I said, I am not so sure if there needs to be a numpy folder to contain the .pyd or not. You seemed to have gone without and not had luck. Since your call stack suggest the loading file thinks it lives in that folder, I would now assume it is needed.

And then of course, for numpy I do not think that --recurse-all is needed at all. It's a very well behaved package actually.

Yours,
Kay

**Comment by brupelo** [comment]
@kayhayen Ok, I've done more testing about this one and yeah, you were right, `numpy` folder containing both the .pyd and .dll files were needed, now the package imports fine using either `--recurse-all` or not. With the main difference of course being the compilation times and the final size of the pyd, (with recurse-all is ~58mb, without recurse-all is ~48mb). Btw, I've also tried to reduce the number of cores in the compilation as my cpu is 8core and by spawning 8 cl processes my laptop would become quite unresponsive... which is a really bad thing as playing tetris while compiling the module would become impractical :'D . Nah, seriously, I've tested using `-j 1` but the compilation time become really bad even if not using `--recurse-all`, ie: ~1600s.

Anyway, if I've understood correctly the right way to proceed here would be:

 - Try to build the package without using `--recurse-all`, test it and it works you're done
 - If the previous step doesn't work try to find which pyd/dlls the final pyd module is using and ship them together, consider the "path" of this module is `site-packages`, is this correct?
 - If the previous step didn't work neither, try --recurse-all and also ship the necessary pyd/dlls as well
 - If the previous step didn't work, ask Kay :)

In any case, I've got an important question if you don't mind. I've got plenty of personal projects where I use custom plugin based architectures and sometimes I do nasty tricks... Eventually I'd like to package them with nuitka but before doing so I'd like to fully understand how this whole thing import mechanism on nuitka works.

Could you please reference me to some blog article, podcast, video, spots on the source, or just providing an explanation that helps me to clarify so I won't have the same question again?

Just for the record, I do fully understand how import mechanisms works in python but when it comes to how nuitka deals with it or how extension modules scans imports is a different ball-park, so that would definitely help.

Thanks for your patience and help.

Yours, 
Bruno

**Comment by kayhayen** [comment]
@brupelo I would appreciate it if the step "2", the gathering of extension modules to copy for "numpy.pyd" below "numpy" would be automated. Maybe you could create the new issue describing what to do, and a PR for it, or mark it as "needs help" tag and enhancement.

With that done, I would extend the "library" test for me to run in a mode, where it would go over all the packages, and not just modules, attempting to compile them that way, of course with only the initial top level import attempted, but still. That test can then be used to eradicate issues, surely.

Actually I think Nuitka is very complex for importing, because it very precisely mimics how pure Python works. The trick with `__path__` to allow finding submodules is about the only one I think that is any special. I have no write up for that yet. The Developer Manual has some information, but not all. I think I will add a chapter about that `__path__` trick now, lest I forget later on how this is worked. Your issue can then reference that.

BTW: Using --recurse-all is considered harmful when creating an extension module, because it will include a lot of that that better be in your "requirements.txt". At least for upstreams packaging their own stuff, it would be totally wrong. It also prevents changes to the code of those to become effective with a single update.

Turning this into a question, because it answers one. Not an issue at all as far as I can see. The potential enhancement to do this automatically should be done by somebody else but me. It would be much like what the freezer is already doing, gathering extension modules and create a distribution folder.
