### ISSUE TITLE
How to use properly compiled extension modules?

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#124]
Here's the thing, let's say I've already built few python extension modules and I've got them stored in a "3rdparty" folder. For instance, imagine something like this:

![libs](https://dl.dropboxusercontent.com/s/cet2nsl5liv4vhw/explorer_2018-09-09_16-16-15.png)

I've already checked that nuitka will use those extensions if that folder has bigger priority than other modules living in sys.path, so for instance, If I make a little test and I put a main.py which uses numpy in "3rdparty" folder, nuitka will make sure that uses numpy.py from 3rdparty instead recompiling again the one living in site-packages ones... So, instead wasting 1200s building numpy again by using numpy.pyd the compilation will just few seconds, which makes total sense as nuitka has only put the right code to load dynamically the shared library numpy.pyd.

Anyway, question is, what's be the correct way so nuitka will inspect the 3rdparty folder before anything else? I've tried to add "3rdparty" into a .pth file in my virtualenv but that won't do it. Another choice would be tweaking PYTHONPATH so you put the 3rdparty folder before anything else... but, is there a more better alternative? I'm asking this cos I really dislike having/tweaking PYTHONPATH at all and I always discourage python newcomers to use that env.var in the first place, using system-wide env.vars is a really bad way to go, similar thing than using system-wide python, it should be forbidden! :)

I've run out of ideas about what's the best way to go about it... you definitely don't want to modify sys.path programmatically neither... But definitely, you don't want to copy or move around python stuff that uses 3rdparty stuff into that folder neither, so... I'm all ears for proper suggestion here :)

**Comment by kayhayen** [comment]
There is one *fundamental* principle to Nuitka and locating stuff. It is supposed to be identical to how CPython does it. To provide modules you Python, you have what you have there:

a) Current directory, although that has falled out of favor for security minded people.
b) Script directory
c) Compiled into CPython paths
d) Added by site.py, what allows you .pth files
e) PYTHONPATH

The basically idea is that Nuitka will get to compile in an environment where CPython will behave the same.

So if you can make CPython load your numpy.pyd file before the numpy in dist-packages you win, otherwise you loose. There are not going to be any configurations to order source code. Why not? Well first step when debugging Nuitka is to check if CPython works.

Nuitka internally does some things to undo the loading of site.py, restarting without it, but preserving the information about sys.path changes and ".pth" created namespace modules. But these all are supposed to be transparent to you.

Therefore, Nuitka follows the odd and history ridden behaviors of CPython. With one limitation, it often had to be taught what metapath based loaders do with code,e.g. "six.moves" or "pkg_resources.vendor" have extra code for that in Nuitka to predict its effects.

**Comment by brupelo** [comment]
Thanks Kay for clarification. Alright, I like that _fundamental_ principle. 

Summing up, before building anything with nuitka you should test the content you want to package on CPython and make sure the modules are imported from the places you want and nuitka will do the same (if not, that'd be an hypothetical bug). So, in my case I need to make sure CPython is already using the 3rdparty pyds in the first place and then I'd be ready to build my project with nuitka, is that correct?

Ok, everything clear to me. I guess PYTHONPATH is the best choice here afterall. One thing I love very much about unix shells such as bash is they allow you to send env.vars to the spawned process with a syntax like `PYTHONPATH=/whatever python main.py` and the system-wide env.var is not modified at all. I don't know any windows shell that allows you do the same, on windows you basically have to set/unset the env.var before/after you create the process, ie: `set PYTHONPATH=c:\whatever; python main.py; set PYTHONPATH=`, which is really uncool... But well, I guess you can wrap that somehow on a 1 button click proper deployment script.

Here's some docs that be useful to future readers:

 - [https://docs.python.org/3/library/site.html](https://docs.python.org/3/library/site.html)
 - [https://docs.python.org/3/tutorial/modules.html#the-module-search-path](https://docs.python.org/3/tutorial/modules.html#the-module-search-path)

Anyway, all clear, if there is any additional useful comments to add, the issue can be closed :)

Yours,
Bruno
