### ISSUE TITLE
Unknown encoding: idna - Using the "requests" library with Nuitka.

### ISSUE THREAD

**Issue by zFlarex** [kayhayen/Nuitka#14]
I am attempting to use the "requests" library with Nuitka.

**test.py**
```
import requests

r = requests.get('http://google.com')

print r.text
```

I compiled a portable version of it using: `>nuitka --portable test.py`.

I can browse to `test.dist` and execute `test.exe` perfectly on my machine.

However when I transfer it to a new VM, I encountered a couple of errors:

1. **ImportError: No module named _socket** - I fixed this by adding "_sockets.pyd"

2. **LookupError: unknown encoding: idna** - I am currently stuck and cannot figure out how to fix this issue, I have tried adding `idna.pyd` (I compiled `idna.py` using Nuitka then added to `test.dist` but to no avail).

**Comment by kayhayen** [comment]
Actually Nuitka detects all available encodings, and forces inclusion of them, with code like this (check Standalone.py:

`
encoding_names = [
        filename[:-3]
        for _path, filename in
        listDir(os.path.dirname(sys.modules["encodings"].__file__))
        if filename.endswith(".py")
        if "__init__" not in filename
]
`

Can you check what this does for you?

**Comment by kayhayen** [comment]
it seems that the difference is that the standalone compiled file still finds through some mechanism the original install, and can load it from there. With "PYTHONHOME=." from the outside, this is no longer the case.

This is kind of surprising, because there is code in Nuitka in "prepareStandaloneEnvironment" which updates it. I imagine it is being too late, due to how "python.lib" may already initialize the DLL, unlike on other platforms. But when I added a trace, I also didn't see it, so maybe it is not or no more done.

Repairing that is likely to reveal issues then.

**Comment by kayhayen** [comment]
I just made a stable release with fixes that ought to cover this. Using Py_SetPath with Python3, and PySys_SetPath after the fact with Python2, this was ruled out, and it was ultimately discovered that idna is using shared libraries which need other shared libraries, but the scan was not recursive. Now it is, and this should be gone.

I am assuming the libraries used there are pretty wide spread normally, or easily another extension could have a direct dependency on it, so this was rare, but consistently happening ever since standalone mode was devised. Should now be much better.
