### ISSUE TITLE
Nuitka producing really huge cpp files in some particular cases

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#141]
Not sure if this should posted elsewhere other than the issue tracker... but definitely is worth mentioning. After all years coding in c/c++ this it's the first time I've found such a huge cpp file O_o

![monster cpp](https://dl.dropboxusercontent.com/s/19axdnfst9azrfs/explorer_2018-09-18_17-21-47.png)

So yeah, congrats about the new world guiness record in that regard :P.... I guess ;) ?

Ps. I've finished writing this issue and cl has been able to generate not only a beautiful obj file of 75Mb out of that file by the whole `py2js` module has been built successfully, hats off to vs' coders, rock solid compiler they've built.

Ps2. In case you wanna check by yourself:

    (py364_32) D:\sources\others\sources_compilers\nuitka_tests>pip show Js2Py
    Name: Js2Py
    Version: 0.59
    Summary: JavaScript to Python Translator & JavaScript interpreter written in 100% pure Python.
    Home-page: https://github.com/PiotrDabkowski/Js2Py
    Author: Piotr Dabkowski
    Author-email: piodrus@gmail.com
    License: MIT
    Location: d:\virtual_envs\py364_32\lib\site-packages
    Requires: tzlocal, pyjsparser, six
    Required-by:

Ps3. Not sure if this should considered just an "anecdotal" or whether it'll be worth optimizing cpp final size... in any case, those are the facts

**Comment by wolfv** [comment]
In fact, internally C++ files after preprocessing are really large, too. Because all #include statements mean that the contents of that file are actually inlined. 

I am not sure if the file get's that large though. Just wanted to say that compilers are "used" to dealing with what seems like large files.

**Comment by brupelo** [comment]
Sure thing, the valid metric to consider in these type of cases are obj files. Guess when I said in my previous post "optimizing" cpp final size I should have said "would it be a good worth producing equally valid c code (in terms of equal speed/correctness) than the existing generated that produces smaller obj files or it's not worth the effort". Said otherwise, is it worth nowadays reducing the badwidth of having to ship my product via final zip/msi/.7z/.rpm/.deb/whatever...  of 200mb instead a 400mb ones? 

Btw, right now compiler flags are adjusted to produce fast code instead small one, nothing to bitch about that. That's definitely a smart default choice in fact, even if the user can change it easily.

**Comment by brupelo** [comment]
@kayhayen Thanks for the clarification! makes total sense and it's clear as water :)

> As for generated code size and speed. The C compiler is damn quick and typically very correct. Trying to create more compact C code in Python, and expecting it to take less time total, is unwise. Obviously I take care to generate C code that leads to the fastest possible machine code. But saving a variable that will be optimized away by the C compiler, there is no point.

Yeah, in fact I'll self-answer myself about that concern of huge size packages when it comes to distribution over the network. Nowadays network bandwidth has become decently fast worldwide (except rare cases/countries) and storage is extremly cheap overall... So worrying whether a package is ~50mb, ~100mb, ~200mb or ~400mb would be a waste of time with little benefits. Unless you're releasing many times per day and uploading your packages to the servers is "expensive", although if deployment is done right you're packaging on the server side anyway :/. Furthermore, as a user you're given the choice to configure the compiler flags as you wish so generating smaller code instead faster one or even use external PE/Coff/Elf compressor is totally doable if necessary... So.. :)

Anyway, consider this thread more like a simple anecdotal/question rather than something useful that can serve to extract conclusion for nuitka improvements.

But yeah, first time I see a 213mb blob of C11 code so it surprised me quite a lot :)

Regards,
B.

**Comment by kayhayen** [comment]
As for binary size, well obviously reducing the object code size often will make things faster. Which is at least in my memory, why -Os and -O2 were one day found to be stupid things with gcc some years ago, and then something changed. Smaller code fits into caches and therefore often is faster.

However, Nuitka will gladly add code that will allow to take shortcuts which save a lot of time, and that is going to only increase. On the other hand, improved static optimization allows for more compact code, e.g. the "bool" target C type work created smaller/faster C code, so code size is going to oscillate and not a good indication of anything.

Can you check out, how much Python code there is at the root of the large C file you are talking about? The constant creation code feeds on a binary blob, and so if something that Nuitka doesn't do, just an example, "list(range(10000000))" were to be compile time computed in a constant, and code generated to create that list, things would be large. But it might make sense to check that is not the case, and there is indeed a lot of Python code behind that.

Otherwise, catching such oversized constants would be good. Nuitka tries to limit everything to 256 somethings for computations. But most of the time, data should not be in that file anyway, so it's only a guess. If you want to look at that, be my guest. Otherwise I will try it out myself eventually, so it's clear this is a question only indeed.

**Comment by kayhayen** [comment]
It appears the Python module in question is 3.7M of Python, something that explains the outstanding size, and an amazing amount of string (unicode) constants in the code. It seems to be generated code, and that explains everything.

Nuitka churns relatively long on it and then the C compiler using 7GB of memory compiling it, which is probably to be expected. Nuitka probably wasn't using too little memory either.

Anyway, I will mark this as invalid, it's just what it has to be.

Yours,
Kay
